# Generated by Django 4.2.14 on 2024-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffeinIntakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caffeinintake',
            name='intakeId',
        ),
        migrations.AddField(
            model_name='caffeinintake',
            name='intake_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
