# Generated by Django 4.2.14 on 2024-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffeinIntakes', '0002_remove_caffeinintake_intakeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffeinintake',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
